### ISSUE TITLE
Feature: third argument to return for when route does not match pattern

### ISSUE THREAD

**Issue by lowerends** [letrunghieu/active#15]
A nice feature would be to have the possibility to add a third argument that would be returned in case the route does not match the given pattern. For example:

    # Return string 'selected' if current URI is /foo or /bar or return string 'not-selected' if current URI is not /foo and not /bar
    Active::pattern(array('foo', 'bar'), 'selected', 'not-selected');

Would this be something you would consider to add? I'd be glad to help with a pull request!

**Comment by letrunghieu** [comment]
You can use native PHP achieve this purpose instead of adding a conditional return statement into each method of the package:

```php
Active::pattern(array('foo', 'bar'), 'selected') ? : 'not-selected'
```

**Comment by lowerends** [comment]
Indeed, but I thought it would be a nice addition to this package to make it more fluent.

**Comment by letrunghieu** [comment]
I think you can make a PR so that I can write performance test for these two options :smile:

**Comment by lowerends** [comment]
Cool, I'll give it a try the coming days.

**Comment by lowerends** [comment]
I just created a pull request for this issue in #16. There's no extra conditional return statements used, so there will be no impact on performance.

**Comment by lowerends** [comment]
Thanks!
