### ISSUE TITLE
Watson conflict slows composer a lot

### ISSUE THREAD

**Issue by loranger** [letrunghieu/active#18]
I don't know why exactly, but composer update spends a lot (lot lot) a time reading and writing cache from watson/active package.

It's really sad because as a conflict it should simply be ignored.

I still don't know what you can do about it, but maybe a simple warning should be better than this network lag on each composer update.

**Comment by letrunghieu** [comment]
Thank you for your information, The package `composer.json` is one of my very first try on building a PHP package. In that time, I wrote many things "as the documentation told me" :smile: . I'll update my json file to more efficiency.

**Comment by letrunghieu** [comment]
Done! Two new minor releases.

**Comment by loranger** [comment]
Lightning fast fix !
Thank you ! :+1:
