### ISSUE TITLE
why you don't update documentation and add new method ?

### ISSUE THREAD

**Issue by AbdullahGhanem** [letrunghieu/active#20]

**Comment by letrunghieu** [comment]
Can you give me more idea about what information need adding?

**Comment by AbdullahGhanem** [comment]
in https://www.hieule.info/products/active-class-helper-laravel-4/

where New method in version 2.*

**Comment by letrunghieu** [comment]
I released a new major version with new API. The documentation for `3.x` version can be found [here](https://www.hieule.info/?p=377). I'm sorry that I have to time to check and update the document of the old version :disappointed:
