### ISSUE TITLE
Route parameters?

### ISSUE THREAD

**Issue by m1r0** [letrunghieu/active#21]
I think it would be a good idea to include the route parameters and not only the route name.

Lets say we need to set an active class for the route `admin/product-types/{product_types}/categories`.

We can do something like (not a very good example but hopefully you get the point):
`Active::route(['admin.product-types.categories.index' => [$product_type->id]])`

**Comment by MozMorris** [comment]
@m1r0 Agreed.

For now, this should do what you want:

```php
Active::pattern(
    ltrim(route('pages.show', $page->slug, false), '/')
);
```

**Comment by letrunghieu** [comment]
I released a minor update for the `2.x` version. Your can see the [release note](https://github.com/letrunghieu/active/releases/tag/2.3.0).

In your case, I suggest using this expression to set the active class when the current route is `admin.product-types.categories.index` and the value of the `product_types` parameter is `1`:

    Active::routeParam('admin.product-types.categories.index', ['product_types' => 1])

**Comment by m1r0** [comment]
@letrunghieu Thanks.
