### ISSUE TITLE
How to handle model binding route??

### ISSUE THREAD

**Issue by gfd6th** [letrunghieu/active#24]
If I have bound the route param to route, eg: /{course}/{episode}, and episode bound with episode model

`if_route_param('episode', $episode)` will return null.

`$this->route->parameter($param)` will return the episode model, and it don't equal $episode model

**Comment by letrunghieu** [comment]
The current version of this package has not supported model binding routes yet. I am going to update the `if_route_param` function to use the `id` property of the model instead of the model object itself in the comparison.

**Comment by letrunghieu** [comment]
Now, this feature is implemented in version [3.2.0](https://github.com/letrunghieu/active/releases/tag/3.2.0)
