### ISSUE TITLE
Error in documentation in - "Check the route parameter value"

### ISSUE THREAD

**Issue by blomdahldaniel** [letrunghieu/active#26]
Hi! I think that this package is nice. 

I did find an error in your documentation at your website though. Just a mistake.
https://www.hieule.info/products/laravel-active-version-3-released/

It is under the header:
> ### Check the route parameter value
> * Use the alias: `Active::checkRouteParam($key, $value)`
> * Use the application container: `app('active')->checkRouteParam($key, $value)`
> * Use the helper function: `if_route_pattern($key, $value)`

The third line is wrong and should be:
* Use the helper function: `if_route_param($key, $value)`

the error is **_pattern** instead of **_param** like it should be

**Comment by letrunghieu** [comment]
Thank you for pointing it out :) I updated the documentation on my website.

**Comment by blomdahldaniel** [comment]
Glad to help! :) Thanks!
