### ISSUE TITLE
Argument 1 passed to if_route() must be of the type array, string given

### ISSUE THREAD

**Issue by jrean** [letrunghieu/active#28]
Hi,

I followed your documentation and when just simply trying the following code I got the error:
> Argument 1 passed to if_route() must be of the type array, string given

`active_class(if_route('xxx.xxx'))`

I have a route named `xxx.xxx`...

You should fix your documentation.

Thank you

**Comment by astroanu** [comment]
+1

**Comment by astroanu** [comment]
i think it's better to make it accept both string and array. casting it to array inside the helper would be better.

**Comment by letrunghieu** [comment]
Now, this feature is implemented in version [3.2.0](https://github.com/letrunghieu/active/releases/tag/3.2.0)
