### ISSUE TITLE
only return '1' if match pattern

### ISSUE THREAD

**Issue by shinnlu** [letrunghieu/active#29]
my code
`
<li class="{{Active::checkUriPattern(['admin']) }}">
  <a href=" {{route('admin.dashboard')}} "><span> Dashboard </span></a>
</li>
`
output
`
<li class="1">
  <a href=" http://xxx.local/admin "><span> Dashboard </span></a>
</li>
`
why it's return '1' not 'active'

**Comment by shinnlu** [comment]
i found the solution:
`
active_class(if_uri_pattern(['admin']), 'active', '')
`
but how to set default output to 'active' and empty

**Comment by letrunghieu** [comment]
I'm sorry for responding late. It's great that you found the solution. I updated the README file so that the "Usage" section become more noticeable. If you're new to this package, [this page](https://www.hieule.info/?p=377) can tell you how to use  "Active".
