### ISSUE TITLE
Missing argument 2 in ActiveServiceProvider.php line 21 with Laravel 5.3

### ISSUE THREAD

**Issue by matbeard** [letrunghieu/active#31]
I've just updated my site to Laravel 5.3 (I know it's not officially released yet, but it's now RC1). I'm now getting the above error.

Maybe something to do with the updated RouteServiceProvider but I'm no expert.

**Comment by letrunghieu** [comment]
I used Laravel 5.3-RC1 and there was no error in `ActiveServiceProvider.php`. Can you give me more details about your setup?

**Comment by matbeard** [comment]
Sorry... I needed a quick fix so I've switched to a different package: `Laravelista\Ekko`, but my problem occurred after updating a 5.2 site to 5.3. Everything else is working fine, so I'm afraid I don't have time to troubleshoot.
