### ISSUE TITLE
Add installation support for Laravel 5.3

### ISSUE THREAD

**Issue by edbentinck** [letrunghieu/active#32]
Now that Laravel 5.3 has [officially been released](https://laravel-news.com/2016/08/laravel-5-3-is-now-released/), it would be awesome if this package could be updated to be installable in new projects.

Currently, running `composer require hieu-le/active` in a new Laravel project errors out with dependency failures.

Thanks, dude! 😃

**Comment by letrunghieu** [comment]
Hi,

I updated the `composer.json` file so that you can install this package with Laravel 5.3 now. 

`composer require hieu-le/active` 

If you cannot see the version 3.3.x is loaded, run this command

`composer require hieu-le/active:^3.3`

**Comment by edbentinck** [comment]
Awesome! It worked.

Thanks and keep up the good work 😃
