### ISSUE TITLE
建议增加 if_query_pattern

### ISSUE THREAD

**Issue by hao-li** [letrunghieu/active#33]
## [Proposal] Add if_query_pattern function

Some libraries use a complex combination of parameter's values.

For example:
[RequestCriteria](https://github.com/andersao/l5-repository#using-the-requestcriteria)  of  [andersao/l5-repository](https://github.com/andersao/l5-repository)

```
http://prettus.local/users?filter=id;name
```

The values (**id** and **name** as well as others) of **filter** could be  dynamic combination.
Can not easily be matched by if_query.

**Comment by letrunghieu** [comment]
For too complicated patterns, I think users should test the conditions by themselves and pass the result into the `active_class` helper function.
