### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by vpratfr** [letrunghieu/active#34]
In the current version, you still have a reference to `app->share` in your service provider.

I see that the development version is using the `app->singleton` method. Could you release an update to get compatibility with L5.4?

**Comment by ninjaparade** [comment]
@vpratfr update your composer dependency to `dev-master` and you should be fine.

https://github.com/letrunghieu/active/blob/master/src/ActiveServiceProvider.php#L43-L54

its been updated to use `$app->singleton`

**Comment by letrunghieu** [comment]
I updated the version number to `3.4.0`
