### ISSUE TITLE
Laravel 6.0

### ISSUE THREAD

**Issue by celcius-jochen** [letrunghieu/active#39]
Will this package support Laravel 6.0?

**Comment by sebastienheyd** [comment]
Is this package still being maintained?

**Comment by celcius-jochen** [comment]
Probably not, his personal blog hasn't been updated in a while and he has almost no github contributions for the last year...

I've just sent him a friendly tweet on twitter (https://twitter.com/ltrunghieu) asking him to either transfer the repo or add a collaborator. Let's hope for the best ...

**Comment by chescos** [comment]
This is an awesome package, would be cool if it would support Laravel 6 in the future!

**Comment by letrunghieu** [comment]
Thank you for all of your support. I'm updating this package (and my other packages). I am going to be more active on GitHub after my long busy time 😄 .

@celcius-jochen thank you for reaching me on Twitter. That message reminds me of my open-source projects that need updating.

**Comment by letrunghieu** [comment]
I've updated this package with the release [4.0.0](https://github.com/letrunghieu/active/releases/tag/4.0.0)
